### ISSUE TITLE
Faster error queue

### ISSUE THREAD

**Issue by mourner** [fogleman/hmm#8]
Another small optimization that you could port back: https://github.com/mapbox/delatin/commit/b69b2f6ce20ce68505a2271b140ed39e225b99b9

Since queue comparisons happen much more often than other operations like swap/push/pop, we can optimize them by keeping all errors in the same order as the queue (instead of a lookup table like queue indices). This gave me a modest ~3-5% improvement on overall running time, and also makes the code slightly easier to understand.

**Comment by fogleman** [comment]
I didn't see any noticeable improvement here, so just gonna leave it as is. Thanks though!
